### ISSUE TITLE
IOS failing due to Airship library linking

### ISSUE THREAD

**Issue by ShMcK** [urbanairship/react-native-module#35]
Cannot reconcile AirshipLib path in IOS.

## Details

The current version of "UARCTMessageViewController.h" path is failing.

```
#import "AirshipLib.h"
```

Prepending the directory fixes the issue.

```
#import "AirshipKit/AirshipLib.h"
```

--- 

## Possible Solution:

In the instructions, it mentions:

> if it's unable to find it for your project due to a non-standard install path or manual installation, you can set AIRSHIP_SEARCH_PATH variable with the location of the framework.

Could you clarify on how this can be done?

**Comment by rlepinski** [comment]
@ShMcK How did you install the SDK?

**Comment by Zyphxion** [comment]
Getting this error too after a manual installation.  Would also like some clarification as to where the AIRSHIP_SEARCH_PATH variable is located

**Comment by ShMcK** [comment]
I eventually got it working using the manual install SDK. 

The directions are no longer included on the [site](https://docs.urbanairship.com/platform/react-native/). 

If the manual installation is added again, I'd suggest a few changes. I think the directions could be be improved, and the download file could filtered of unused files and folders. There were several possible interpretations.

**Comment by rlepinski** [comment]
@Zyphxion If possible, I recommend the use of cocoapods instead of trying to manual install the SDK. It will make installation and updating it easier.

For manual install, follow: https://docs.urbanairship.com/platform/ios/#manual. You will download a zip that contains the SDK. Within it is a folder AirshipKit. You need to set `AIRSHIP_SEARCH_PATH` to the folders location.

**Comment by Zyphxion** [comment]
@ShMcK What ended up being your manual install solution?  It looks like I'm getting the same "AirshipLib.h not found" err with a Cocopods install..

**Comment by rlepinski** [comment]
@Zyphxion did you run pod update and verify the pod installed? It should work without an issue with cocoapods

**Comment by rlepinski** [comment]
@ShMcK I see that we have a mismatch between `UARCTMessageViewController.h` and the rest of the header files. We will patch it soon.

**Comment by rlepinski** [comment]
Fixed in 1.2.2

**Comment by jorgedavila25** [comment]
I'm using 1.2.2 and still having this issue even w/ using pods. How do i go about setting the `AIRSHIP_SEARCH_PATH`? Thanks

**Comment by rlepinski** [comment]
@jorgedavila25 You should not have to set the `AIRSHIP_SEARCH_PATH` if you are using cocoapods. Please contact support or open a new issue so we can resolve your issue instead of working around it.
