### ISSUE TITLE
getSubscriptionLists() method is missing

### ISSUE THREAD

**Issue by raquelmsmith** [urbanairship/react-native-module#390]
# Preliminary Info

### What Airship dependencies are you using?

13.1.1

# Report

### What unexpected behavior are you seeing?
I am looking to subscribe/unsubscribe people from subscription lists. The `UrbanAirship.editSubscriptionLists()` method exists, but `UrbanAirship.getSubscriptionLists()` does not. It seems to exist for Android as per the docs: https://docs.airship.com/platform/android/preference-center/#building-your-own-preference-center-ui

I need this method so that I can know which lists the user is subscribed to when populating the UI.

Thank you!

**Comment by rlepinski** [comment]
Thanks for the report, will try to address for next release

**Comment by rlepinski** [comment]
Added in 13.2.0

**Comment by raquelmsmith** [comment]
@rlepinski I'm finally getting back around to this. When I use 

```
UrbanAirship.editChannelSubscriptionLists().subscribe('my_list')
UrbanAirship.editChannelSubscriptionLists().apply()

```

And then later

```
    UrbanAirship.getSubscriptionLists()
      .then((res) => console.log(res, "THE LISTS"))
      .catch((err) => console.log(err, "THE ERR"))
```

I get on ios `{"channel": []} THE LISTS` and on Android `[Error: Failed to fetch contact subscription lists.] THE ERR`. So iOS never actually creates the subscription (I do have it registered in the Airship dashboard), and Android just errors when I try to get the lists. 

![image](https://user-images.githubusercontent.com/18598166/163242635-3df2f507-f6bb-41ea-990a-072ece0e6d3f.png)

Am I using these incorrectly?

**Comment by rlepinski** [comment]
@raquelmsmith Each `editSubscriptionList()` creates its own editor instance. You will want to either chain them like this:
```
UrbanAirship.editChannelSubscriptionLists()
    .subscribe('recipe_suggestions')
    .apply()
```

Or it might be more idiomatic for js/ts to use a var to hold it:
```
const editor = UrbanAirship.editChannelSubscriptionLists()
editor.subscribe('recipe_suggestions')
editor.apply()
```

**Comment by raquelmsmith** [comment]
Ah ok i didn't realize that, changing it to chain the apply() works in iOS! However, I still can't even do getSubscriptionLists() on android. Any ideas?

**Comment by rlepinski** [comment]
@raquelmsmith I see two problems with Android, missing break statements (swift habits!) and parsing the types wrong. It will always pull and only use the first type you supply, and it will always fall through to contacts. If you have disabled contacts it wont work.

Ill try to get a patch tomorrow.

**Comment by raquelmsmith** [comment]
Awesome thanks so much!!

**Comment by rlepinski** [comment]
@raquelmsmith should be fixed in 14.2.0

**Comment by vuthanhtrung0504** [comment]
This issue still happened to me in 14.2.0. getSubscriptionLists only return data after you subscribe else it always returns the message: "Failed to fetch contact subscription lists". Any idea?

**Comment by rlepinski** [comment]
@vuthanhtrung0504 It could be caused by a few issues:
- Do you have contacts and tagsAndAttributes features enabled?
- Do you have internet connectivity?
- Do you have a channel created yet?

Assuming you have the features enabled, you should just retry on failure. If its always failing for you though, it's probably another issue. I realize the current error message is not that helpful on debugging this, we will see if we can make it more clear in the future.

**Comment by vuthanhtrung0504** [comment]
@rlepinski Channel was created, the internet connection also worked well, and all features were enabled. Every time I reloaded the app and fetched it again, the data were different

**Comment by rlepinski** [comment]
@vuthanhtrung0504 could you please open a new issue so we can keep track of it. We will need verbose logs enabled to see whats going on.
